# define PJMEDIA_VIDEO_DEV_HAS_FFMPEG 1
# define PJMEDIA_HAS_FFMPEG 1
# define PJMEDIA_HAS_VIDEO 1
# define PJMEDIA_VIDEO_DEV_HAS_SDL 1
# define PJMEDIA_VIDEO_DEV_SDL_HAS_OPENGL 1
# define PJMEDIA_HAS_FFMPEG_CODEC_H264 1
#define PJ_CONFIG_IPHONE 1
#include <pj/config_site_sample.h>
